### ISSUE TITLE
Nginx-proxy solution isn't working at all

### ISSUE THREAD

**Issue by inakiabt** [inakiabt/docker-media-center#2]

**Comment by inakiabt** [comment]
This could be an alternative https://www.linuxserver.io/2018/02/03/using-traefik-as-a-reverse-proxy-with-docker/

**Comment by hschne** [comment]
I stumbled on your repo searching for inspiration. Nice setup, helped me a lot.

Tried traefik, here's a minimal docker-compose that works for me.

``` yaml
version: '3.5' 

services:
 
  traefik: 
    image: traefik
    container_name: traefik
    restart: unless-stopped
    command: --web --docker --docker.domain=localhost
    ports: 
      - 8080:8080 
      - 80:80
    networks: 
      - aresnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels: 
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.localhost" 
      - "traefik.port=8080"

  emby: 
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    networks:
      - aresnet
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - $HOME/.config/embyserver:/config
      - /media/media/:/media
    environment: 
      - AUTO_UPDATES_ON=true
      - UID=1000
      - GID=1000
    labels: 
      - "traefik.backend=emby"
      - "traefik.frontend.rule=Host:emby.localhost"
      - "traefik.port=8096" 
    

networks:
  aresnet:
    name: aresnet
    driver: bridge
```

You should then be able to visit Traefik using ``ltraefik.localhost`` and Emby using ``emby.localhost``.
